In [3]:
import numpy as np

In [4]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [5]:
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

In [6]:
training_outputs = np.array([[0,1,1,0]]).T

In [7]:
np.random.seed(1)

In [8]:
synaptic_weights = 2 * np.random.random((3,1))-1

In [9]:
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [11]:
print("Random Starting Synaptic Weights: ", synaptic_weights)

Random Starting Synaptic Weights:  [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [12]:
print(synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [13]:
for iteration in range(1):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    print("Outputs after Training: ")
    print(outputs)

Outputs after Training: 
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]


In [14]:
import numpy as np

In [15]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [16]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [17]:
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1))-1
print("Random Starting Synaptic Weights: ")
synaptic_weights

Random Starting Synaptic Weights: 


array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [35]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T,adjustments)

print("Synaptic Weights after Training: ")
print(synaptic_weights)
print("Output after Training: ",)
print(outputs)

Synaptic Weights after Training: 
[[11.78376704]
 [-0.20460659]
 [-5.68765926]]
Output after Training: 
[[0.0033761 ]
 [0.99724477]
 [0.99775343]
 [0.00275313]]


In [24]:
#Design 2-input AND Gate training process using ANN

In [25]:
#Problem Mapping

In [26]:
import numpy as np

In [27]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [37]:
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1))-0
print("Random Starting Synaptic Weights: ")
synaptic_weights

Random Starting Synaptic Weights: 


array([[8.34044009e-01],
       [1.44064899e+00],
       [2.28749635e-04]])

In [39]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T,adjustments)

print("Synaptic Weights after Training: ")
print(synaptic_weights)
print("Output after Training: ",)
print(outputs)

Synaptic Weights after Training: 
[[10.47741794]
 [-0.20607592]
 [-5.03326221]]
Output after Training: 
[[0.00647546]
 [0.99471749]
 [0.99569701]
 [0.00527591]]
